// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrcERl7UziegxHeR6fYr-VFameEr7J2e8',
    appId: '1:226614486302:web:2364443c0b689aaf95550f',
    messagingSenderId: '226614486302',
    projectId: 'dayscript-746bd',
    authDomain: 'dayscript-746bd.firebaseapp.com',
    storageBucket: 'dayscript-746bd.firebasestorage.app',
    measurementId: 'G-WH26LRJK2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ULteG_TMI-m72tV5kBi0ucnN7VrQI98',
    appId: '1:226614486302:android:6fb526f84097cfff95550f',
    messagingSenderId: '226614486302',
    projectId: 'dayscript-746bd',
    storageBucket: 'dayscript-746bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCDvuBmzTF2sYSEUBh_-6Z_QeH-mnctY',
    appId: '1:226614486302:ios:c81d533d270e452f95550f',
    messagingSenderId: '226614486302',
    projectId: 'dayscript-746bd',
    storageBucket: 'dayscript-746bd.firebasestorage.app',
    iosBundleId: 'com.example.myPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApCDvuBmzTF2sYSEUBh_-6Z_QeH-mnctY',
    appId: '1:226614486302:ios:c81d533d270e452f95550f',
    messagingSenderId: '226614486302',
    projectId: 'dayscript-746bd',
    storageBucket: 'dayscript-746bd.firebasestorage.app',
    iosBundleId: 'com.example.myPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrcERl7UziegxHeR6fYr-VFameEr7J2e8',
    appId: '1:226614486302:web:89e630533652a7ab95550f',
    messagingSenderId: '226614486302',
    projectId: 'dayscript-746bd',
    authDomain: 'dayscript-746bd.firebaseapp.com',
    storageBucket: 'dayscript-746bd.firebasestorage.app',
    measurementId: 'G-Y3YECRNSPC',
  );
}
